import { toastMessageTypes } from 'state/snackbars/types';

export const ICON_NAMES = {
  ADMIN: {
    NOT_MODERATED_EVENT: 'notModeratedEventIcon',
    CATEGORIES: 'categoriesIcon',
    SUB_CATEGORIES: 'subCategoriesIcon',
  },
  TAB_BAR: {
    HOME: 'homeTabIcon',
    MAP: 'mapTabIcon',
    CREATE: 'createTabIcon',
    REQUEST: 'RequestIcon',
    TICKET: 'tickeTabIcon',
    PROFILE: 'profileTabIcon',
  },
  TICKET: 'ticketBoldIcon',
  TICKET_EMPTY: 'ticketEmptyIcon',
  TRIP: 'tripIcon',
  EVENT_WARNING: 'eventWarningIcon',
  ARROW: {
    LEFT: 'arrowLeftIcon',
    RIGHT: 'arrowRightIcon',
  },
  MESSAGE: 'messageIcon',
  NOTIFICATION: 'notificationIcon',
  PROFILE: {
    FRIENDS: 'friendsIcon',
    EVENTS: 'eventsIcon',
    GROUPS: 'groupIcon',
    TRIPS: 'tripsIcon',
    PREFERENCES: 'preferencesIcon',
    LANGUAGE: 'languageIcon',
    PRIVACY_POLICY: 'privacyPolicyIcon',
    TERMS_AND_CONDITION: 'termsAndConditionIcon',
    LOGOUT: 'logoutIcon',
    NOTIFICATION_AND_SOUND: 'notificationAndSoundIcon',
  },
  PLUS: 'plusIcon',
  FILTER: 'filterIcon',
  MINUS: 'minusIcon',
  LANGUAGE: 'LanguageIcon',
  LOCATION: 'locationIcon',
  MY_LOCATION: 'myLocationIcon',
  PIN_LOCATION: 'pinLocationIcon',
  CURRENT_LOCATION: 'currentLocationIcon',
  CALENDAR: 'calendarIcon',
  TIME: 'timeIcon',
  TOPIC: 'topicIcon',
  DURATION: 'durationIcon',
  GALLERY_ADD: 'galleryAddIcon',
  INPUT_BTN: {
    CLEAR: 'Clear',
    EYE_OPEN: 'EeyOpen',
    EYE_CLOSE: 'EyeClose',
  },
  SEARCH: 'searchIcon',
  SAVE: 'saveIcon',
  MORE_ICON: 'moreIcon',
  LIST: 'listIcon',
  LOCK: 'lockIcon',
  COMPASS: 'compassIcon',
  EDIT: 'editIcon',
  EDIT_PROFILE: 'editProfileIcon',
  REMOVE: 'removeIcon',
  UNLOCK: 'unlockIcon',
  SHARE: 'shareIcon',
  WARNING: 'warningIcon',
  SETTINGS: 'settingIcon',
  USER: 'userIcon',
  PREMIUM: 'premiumIcon',
  EMPTY_STATES: {
    CHOOSE_SPEAKER: 'EmptyChooseSpeakerIcon',
    NOTIFICATION: 'EmptyNotificationIcon',
    GROUPS: 'EmptyGroupsIcon',
    EVENTS: 'EmptyEventsIcon',
  },
  FLAGS: {
    RU: 'ru',
    AM: 'hy',
    EN: 'en',
  },
  CHECKBOX: {
    RECTANGLE: 'rectangle_checkbox',
    CIRCLE: 'circle_checkbox',
    ON: 'checkbox_onIcon',
    OFF: 'checkbox_off',
  },
  BUTTON_ICON: {
    FB: 'FB',
    VK: 'VK',
    INST: 'INST',
    APPLE: 'APPLE',
    GOOGLE: 'GOOGLE',
    LINKEDIN: 'LINKEDIN',
  },
  ASSETS_SVG: {
    CHECKBOX: 'Checkbox',
    ARROW_LEFT: 'ArrowLeft',
    CROP_PHOTO: 'CropPhoto',
    SEARCH: 'Search',
  },
  TOAST: {
    [toastMessageTypes.ERROR]: 'toastErrorIcon',
    [toastMessageTypes.INFO]: 'toastInfoIcon',
    [toastMessageTypes.WARNING]: 'toastWarningIcon',
    [toastMessageTypes.SUCCESS]: 'toastSuccessIcon',
  },
};
