export const ICON_NAMES = {
  TAB_BAR: {
    HOME: 'homeTabIcon',
    MAP: 'mapTabIcon',
    CREATE: 'createTabIcon',
    TICKET: 'tickeTabIcon',
    PROFILE: 'profileTabIcon',
  },
  ARROW: {
    LEFT: 'arrowLeftIcon',
    RIGHT: 'arrowRightIcon',
  },
  MESSAGE: 'messageIcon',
  NOTIFICATION: 'notificationIcon',
  PROFILE: {
    FRIENDS: 'friendsIcon',
    EVENTS: 'eventsIcon',
    TRIPS: 'tripsIcon',
    PREFERENCES: 'preferencesIcon',
    LANGUAGE: 'languageIcon',
    PRIVACY_POLICY: 'privacyPolicyIcon',
    TERMS_AND_CONDITION: 'termsAndConditionIcon',
    LOGOUT: 'logoutIcon',
    NOTIFICATION_AND_SOUND: 'notificationAndSoundIcon',
  },
  LANGUAGE: 'LanguageIcon',
  LOCATION: 'locationIcon',
  MY_LOCATION: 'myLocationIcon',
  PIN_LOCATION: 'pinLocationIcon',
  CURRENT_LOCATION: 'currentLocationIcon',
  CALENDAR: 'calendarIcon',
  TIME: 'timeIcon',
  TOPIC: 'topicIcon',
  DURATION: 'durationIcon',
  GALLERY_ADD: 'galleryAddIcon',
  INPUT_BTN: {
    CLEAR: 'Clear',
    EYE_OPEN: 'EeyOpen',
    EYE_CLOSE: 'EyeClose',
  },
  SEARCH: 'searchIcon',
  LIST: 'listIcon',
  LOCK: 'lockIcon',
  UNLOCK: 'unlockIcon',
  BUTTON_ICON: {
    FB: 'FB',
    VK: 'VK',
    INST: 'INST',
    APPLE: 'APPLE',
    GOOGLE: 'GOOGLE',
    LINKEDIN: 'LINKEDIN',
  },
  ASSETS_SVG: {
    CHECKBOX: 'Checkbox',
    ARROW_LEFT: 'ArrowLeft',
    CROP_PHOTO: 'CropPhoto',
    SEARCH: 'Search',
  },
};
