export const routNames = {
  START: 'Start',
  AUTH_LAYER: 'AuthLayer',
  APP_LAYER: 'AppLayer',
  FORGOT: 'Forgot',
  CODE_VERIFICATION: 'CodeVerification',
  EVENTS: 'EventsScreen',
  LOGIN: 'Login',
  MAIN_TAB: 'mainTab',
  SETTINGS: 'settingsScreen',
  COMPASS: 'Compass',
  HOME: 'homeScreen',
  MAP: 'mapScreen',
  TRIP: 'tripScreen',
  CHOOSE_LOCATION: 'chooseLocationScreen',
  CREATE_EVENT: 'createEvent',
  CREATE_GROUP: 'createGroup',
  GROUPS: 'groupsScreen',
  PROFILE: 'profileScreen',
  UPLOAD_PHOTO: 'UploadPhoto',
  PREFERENCES: 'PreferencesScreen',
  RESET: 'Reset',
  SIGN_UP_USER_DATA: 'SignUpUserData',
};
