export const routNames = {
  AUTH_LAYER: 'AuthLayer',
  APP_LAYER: 'AppLayer',
  FORGOT: 'Forgot',
  CODE_VERIFICATION: 'CodeVerification',
  LOGIN: 'Login',
  REGISTRATION: 'Registration',
  MAIN_TAB: 'mainTab',
  COMPASS: 'Compass',
  HOME: 'homeScreen',
  TRIP: 'tripScreen',
  EVENTS: 'eventScreen',
  CREATE_EVENT: 'createEvent',
  GROUPS: 'groupsScreen',
  PROFILE: 'profileScreen',
};
