//------------------- TAB BAR -----------------------
export * from './EventsIcon';
export * from './Chat';
export * from './CreateIcon';
export * from './UserIcon';
export * from './Mentor';
export * from './worldIcon';
export * from './mapIcon';
export * from './Routing';
export * from './GroupIcon';
export * from './RequestIcon';
//------------------- TAB BAR -----------------------
