export const olympicsChampions=[
    {
        id:1,
        lName:'Artur',
        fName:'Aleksanyan',
        birthDay:' 21 OCT 1991',
        championsDate:'2010',
        photo:'https://wrestlingtv.in/wp-content/uploads/2020/08/1-39-2.jpg',
        sport:'Struggle',
        sportImage:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Wrestling_pictogram.svg/1200px-Wrestling_pictogram.svg.png',
        country:'ARM',
        flag:'https://www.worldatlas.com/img/flag/am-flag.jpg',
        height: '1.85',
        weight: '96',
        career:'Aleksanyan was born in Gyumri. He started Greco-Roman wrestling in 2000 under the guidance of his father Gevorg Aleksanyan, an honored coach of Armenia. He competed in several junior tournaments and became a Junior World Champion at 84 kg in 2010. In 2011, Aleksanyan moved up a weight class to 96 kg and began competing as a senior.',
    },
    {
        id:2,
        lName:'Artur',
        fName:'Aleksanyan',
        birthDay:' 21 OCT 1991',
        championsDate:'2010',
        photo:'https://wrestlingtv.in/wp-content/uploads/2020/08/1-39-2.jpg',
        sport:'Struggle',
        sportImage:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Wrestling_pictogram.svg/1200px-Wrestling_pictogram.svg.png',
        country:'ENG',
        flag:'https://www.norden.org/sites/default/files/images/Svensk%2520flag693684.jpeg',
        height: '1.85',
        weight: '96',
        career:'Aleksanyan was born in Gyumri. He started Greco-Roman wrestling in 2000 under the guidance of his father Gevorg Aleksanyan, an honored coach of Armenia. He competed in several junior tournaments and became a Junior World Champion at 84 kg in 2010. In 2011, Aleksanyan moved up a weight class to 96 kg and began competing as a senior.',
    },
    {
        id:3,
        lName:'Artur',
        fName:'Aleksanyan',
        birthDay:' 21 OCT 1991',
        championsDate:'2010',
        photo:'https://wrestlingtv.in/wp-content/uploads/2020/08/1-39-2.jpg',
        sport:'Struggle',
        sportImage:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Wrestling_pictogram.svg/1200px-Wrestling_pictogram.svg.png',
        country:'FR',
        flag:'https://www.worldatlas.com/img/flag/am-flag.jpg',
        height: '1.85',
        weight: '96',
        career:'Aleksanyan was born in Gyumri. He started Greco-Roman wrestling in 2000 under the guidance of his father Gevorg Aleksanyan, an honored coach of Armenia. He competed in several junior tournaments and became a Junior World Champion at 84 kg in 2010. In 2011, Aleksanyan moved up a weight class to 96 kg and began competing as a senior.',
    }
]


